### ISSUE TITLE
Empty Symbol Table

### ISSUE THREAD

**Issue by Wh1terat** [PAGalaxyLab/vxhunter#14]
Hi,

Firstly just want to say thanks for putting the time into this project!

Currently working on a SuperH VXWorks 5.5.1 target - it appears to have had the Symbols stripped but the table is still there (albeit empty) so fails to find the symbol table end:

```python
vxhunter_firmware_init.py> Running...
[INFO    ][vxhunter_core.find_symbol_table] symbol table start offset: 0x1fd6cde
[INFO    ][vxhunter_core._check_load_address] Load address is 0x80002000L
[INFO    ][vxhunter_firmware_init.<module>] Analyze Load Address takes 105.375 seconds
[INFO    ][vxhunter_firmware_init.<module>] Rebase image takes 0.049 seconds
unsupported operand type(s) for +: 'NoneType' and 'long'
vxhunter_firmware_init.py> Finished!
```

**Comment by dark-lbp** [comment]
Hi @Wh1terat can you share the VxWorks image?

**Comment by Wh1terat** [comment]
Hi @dark-lbp, I can email you a link privately ?

**Comment by dark-lbp** [comment]
Sure, you can send to jtrkid at gmail dot com.

**Comment by dark-lbp** [comment]
@Wh1terat Thanks for report this issue, current dev branch should fix this bug.
