### ISSUE TITLE
Use cmdj instead of cmd

### ISSUE THREAD

**Issue by Maijin** [PAGalaxyLab/vxhunter#6]
Hello o/,

Just a quick note, when you retrieve information from commands such as fs, o etc. Strongly recommened you use cmdj and the json equivalent command (`fsj`, `oj` etc.) instead of parsing the output manually and risk that your script breaks when a new display of the command is out!

Best Regards,

**Comment by dark-lbp** [comment]
Thank you for your advice, I will try to use cmdj command instead.

**Comment by dark-lbp** [comment]
Updated to master branch. Thanks again for your advice.
