### ISSUE TITLE
Error occurred when analysing a TP-Link firmware

### ISSUE THREAD

**Issue by cq674350529** [PAGalaxyLab/vxhunter#8]
Recently I use vxhunter to auto-analyse a binary file extracted from a TP-Link firmware. During the auto-rebase procedure, an error occurred.

```python
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "D:/Program Files/IDA 7.0/plugins/vxhunter_ida.py", line 962, in run
    self.handler_auto_fix_idb()
  File "D:/Program Files/IDA 7.0/plugins/vxhunter_ida.py", line 820, in handler_auto_fix_idb
    self.fix_vxworks_idb(load_address, vx_version, symbol_table_start, symbol_table_end)
  File "D:/Program Files/IDA 7.0/plugins/vxhunter_ida.py", line 848, in fix_vxworks_idb
    symbol_table_end += load_address
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'long'
```
It seems due to the lack of symbol table.

Any advice would be appreciated! Thanks in advance.

PS: the related firmware is as follows.
[firmware.zip](https://github.com/PAGalaxyLab/vxhunter/files/3808527/firmware.zip)

**Comment by dark-lbp** [comment]
Please Try 4e2c83b0fab2bad2f460df5a163d5808c49777a3 this commit, it support load VxWorks symbol file from firmware.

Step1: Using binwalk to extract firmware, find VxWorks image and Symbol file.
```
➜  tp-link binwalk -e TL-WDR7660_V1.0_2.0.16_Build_190325_Rel.71480n.bin

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
512           0x200           uImage header, header size: 64 bytes, header CRC: 0xDEFB3DA, created: 2018-09-05 07:32:57, image size: 48928 bytes, Data Address: 0x41C00000, Entry Point: 0x41C00000, data CRC: 0x2A36A3AD, OS: Firmware, CPU: ARM, image type: Standalone Program, compression type: lzma, image name: "U-Boot 2014.04-rc1-gdbb6e75-dirt]"
576           0x240           LZMA compressed data, properties: 0x5D, dictionary size: 67108864 bytes, uncompressed size: -1 bytes
66560         0x10400         LZMA compressed data, properties: 0x6E, dictionary size: 8388608 bytes, uncompressed size: 3580296 bytes
```
Goto extracted folder, file **10400** is VxWorks image, and file **140B96** is VxWorks symbol file.

Step2: Load VxWorks image at address 0x00, then load symbol file. VxHunter will rebase image to correct loading address and load the symbols from VxWorks symbol file.

![image](https://user-images.githubusercontent.com/3477662/68210694-08c82580-0011-11ea-85c3-c9c906bb6b94.png)
Chose extracted VxWorks symbol file **140B96**
![image](https://user-images.githubusercontent.com/3477662/68210814-4cbb2a80-0011-11ea-9bf0-6aa4c0528cc0.png)
Wait VxHunter finish analyze, and have fun ^ ^
![image](https://user-images.githubusercontent.com/3477662/68210980-a1f73c00-0011-11ea-82e4-87f30c3015bc.png)

**Comment by cq674350529** [comment]
@dark-lbp Thanks! It works for me.

**Comment by zhjygit** [comment]
Can you give me the vxhunter file for ida？
I have fixed some errors of the python script，but no results with long running。
For example，is it necessary to add base value like “known_address = [0x40205000,0x80002000, 0x10000, 0x1000, 0xf2003fe4, 0x100000, 0x107fe0]”？
However，i cannot find 0x40205000 base address mannully.

**Comment by dark-lbp** [comment]
> Can you give me the vxhunter file for ida？ I have fixed some errors of the python script，but no results with long running。 For example，is it necessary to add base value like “known_address = [0x40205000,0x80002000, 0x10000, 0x1000, 0xf2003fe4, 0x100000, 0x107fe0]”？ However，i cannot find 0x40205000 base address mannully.

You mean the firmware @cq674350529 used?
